terraform:
  backend_type: s3
  backend:
    s3:
      bucket: "orcid-terraform-state-devatmos"
      dynamodb_table: "terraform_state_lock_dynamo_devatmos"
      acl: "bucket-owner-full-control"
      encrypt: true
      key: "terraform.tfstate"
      region: "us-east-2"

vars:
  stage: dev
  environment: ue2

components:
  terraform:
    vpc:
      metadata:
        component: vpc
      vars:
        region: us-east-2


    s3-bucket-example:
      metadata:
        component: s3-bucket
      vars:
        region: us-east-2
        name: atmos-s3-bucket-example
        #vpc_id: '{{ (atmos.Component "vpc" "ue2-dev").outputs.vpc_id }}'


